### PR TITLE
Fixes to compose collect functions

### LINKED ISSUE #95: Side effects are not cached if there are no observers.
Hi ! The Orbit documentation said that [Side effects are cached if there are no observers, guaranteeing critical events such as navigation are delivered after re-subscription.](https://orbit-mvi.org/Core/overview#:~:text=Side%20effects%20are%20cached%20if%20there%20are%20no%20observers%2C%20guaranteeing%20critical%20events%20such%20as%20navigation%20are%20delivered%20after%20re%2Dsubscription.)

But with this sample : 

```
class MainActivity : ComponentActivity() {

    private val buttonViewModel: ButtonViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ButtonToClick(buttonViewModel, ::handleSideEffect)
        }
    }

    private fun handleSideEffect(sideEffect: ButtonSideEffect) {
        when (sideEffect) {
            is ButtonSideEffect -> Toast.makeText(this, sideEffect.message, Toast.LENGTH_LONG).show()
        }
    }
}

sealed class ButtonState
object IdleState: ButtonState()
object ClickedState: ButtonState()

data class ButtonSideEffect(val message: String)

@Composable
fun ButtonToClick(buttonViewModel: ButtonViewModel, handleSideEffect: (ButtonSideEffect) -> Unit = {}) {
    val buttonState = buttonViewModel.container.stateFlow.collectAsState().value

    LaunchedEffect(buttonViewModel) {
        launch {
            buttonViewModel.container.sideEffectFlow.collect { sideEffect ->
                handleSideEffect(sideEffect)
            }
        }
    }

    Button(onClick = { buttonViewModel.onButtonClicked() }, enabled = buttonState is IdleState){
        Text(text = "Click me")
    }
}

class ButtonViewModel: ViewModel(), ContainerHost<ButtonState, ButtonSideEffect> {
    override val container: Container<ButtonState, ButtonSideEffect> = container(IdleState){
        intent { reduce { IdleState } }
    }

    fun onButtonClicked() = intent {
        reduce { ClickedState }

        delay(5000)
        postSideEffect(ButtonSideEffect("Button clicked"))

        reduce { IdleState }
    }
}
```

When I :
1. Click the button
2. Turn off my phone screen
3. Wait for 5 second 
4. Turn it back on

the Toast doesn't appear.

In my "real world" scenario the SideEffect is a navigation event happening on a loading screen. The loading take a while and if the user put is phone aside and come back later, he's stuck on the loading screen.

Am I doing someting wrong with the collection of the side effects ?

### PR DESCRIPTION
**Pull request by mattmook**
Compose updated to 1.1.0-rc03, necessary because project depends on Kotlin 1.6.10
Tests added to verify functions work as expected

Fixes #95

### CODE REVIEW

File: orbit-compose/src/test/kotlin/org/orbitmvi/orbit/compose/ContainerHostExtensionsKtTest.kt [hunk 1]
```diff
@@ -0,0 +1,216 @@
...
+        // Ensure there are no subscribers
+        assertEquals(0, testSubscribedCounter.counter)
+
+        // Start and ensure there is one subscriber
+        mockLifecycleOwner.dispatchEvent(Lifecycle.Event.ON_START)
+        assertEquals(1, testSubscribedCounter.counter)
+    }
+
+    @Test
+    fun `sas tate unsubscribes on stop`() {
```
Comment (Rosomack) [inline orbit-compose/src/test/kotlin/org/orbitmvi/orbit/compose/ContainerHostExtensionsKtTest.kt:146]:
```suggestion
    fun `as state unsubscribes on stop`() {
```

**Review by Rosomack — APPROVED** [review]
